#!/usr/bin/env bash

set -euo pipefail

git checkout -b automatic-maintenance-upgrade-deps

upgraded="$(npx ncu -u --jsonUpgraded)"
npm i

commit_message_title="Upgrade dependencies"
commit_message_body="$(echo $upgraded | jq -r 'keys[] as $k | "\($k): \(.[$k])"')"

git add package.json
git commit -m "$(printf ${commit_message_title}'\n\n'${commit_message_body})"