#!/usr/bin/env bash

set -euo pipefail

git checkout -b upgrade-dependencies

upgraded="$(npx ncu -u --jsonUpgraded)"
npm i

commit_message_title="Upgrade dependencies"
commit_message_body="$(echo $upgraded | jq -r 'keys[] as $k | "\($k): \(.[$k])"')"
commit_message="${commit_message_title}"$'\n\n'"${commit_message_body}"

git add -u .

git commit -m "${commit_message}"