#!/usr/bin/env bash

set -euo pipefail

for cmd in node npm npx; do
  if ! command -v $cmd &> /dev/null; then
    echo "::error:: $cmd is not installed"
    exit 0
  fi
done

if ! npm list --depth=0 --json | jq --exit-status '.dependencies["npm-check-updates"]' &> /dev/null; then
  echo "::error:: npm-check-updates is not installed"
  exit 0
fi

npx ncu -e 2