name: "Automatic npm-check-updates"
description: >-
  This action provides an _opinionated workflow_ for updating dependencies in a
  Node.js project.
author: "Fardjad Davari"
inputs:
  source-branch:
    description: "The branch to create the PR with changes from."
    default: "automatic-npm-check-updates"
  target-branch:
    description: >-
      The branch to merge the changes into. Defaults to `github.head_ref` or 
      `github.ref_name`.
    default: "${{ github.head_ref || github.ref_name }}"
  github-token:
    description: >-
      The GitHub PAT to use for creating, approving, and merging the PR with 
      the changes.
    required: true
  post-update-commands:
    description: >-
      The commands to run after updating the dependencies. They will be 
      executed in a bash shell.
    default: |
      npm install
      npm audit fix --quiet --no-progress --no-fund || true

      npm version patch --no-git-tag-version
  verify-script:
    description: >-
      The script to run to verify the changes. This could be used to run 
      tests, etc.
    default: |
      npm run test
  commit-title:
    description: "The commit title."
    default: "Upgrade dependencies"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check the dependencies
      shell: bash
      run: |
        for cmd in npm npx node; do
          command -v $cmd >/dev/null || exit 1
        done
    - name: Automatic maintenance
      uses: fardjad/my-actions/automatic-maintenance@main
      with:
        source-branch: ${{ inputs.source-branch }}
        target-branch: ${{ inputs.target-branch }}
        github-token: ${{ inputs.github-token }}

        prepare-script: |
          #!/usr/bin/env bash

          set -euo pipefail

          pushd "${{ github.action_path }}/node-commit-message-preprocessor"
          npm install
          npm link
          popd
          command -v commit-message-preprocessor >/dev/null || exit 1

          npm install -g npm-check-updates
          command -v ncu >/dev/null || exit 1
        check-script: |
          #!/usr/bin/env bash

          set -euo pipefail

          npm-check-updates --errorLevel 2
        change-script: |
          #!/usr/bin/env bash

          set -euo pipefail

          npm-check-updates -u --jsonUpgraded > "${{ runner.temp }}/upgraded.json"

          ${{ inputs.post-update-commands }}
        verify-script: ${{ inputs.verify-script }}
        commit-script: |
          #!/usr/bin/env bash

          set -euo pipefail

          git add -u .
          cat <<COMMIT_SCRIPT_EOF | commit-message-preprocessor | git commit -F -
          ${{ inputs.commit-title }}

          $(cat "${{ runner.temp }}/upgraded.json")
          COMMIT_SCRIPT_EOF
